version: "2"
services:
  #  markers-server:
  #    build: .
  #    container_name: markers-server
  #    environment:
  #      - NODE_ENV=development
  #    volumes:
  #      - .:/app
  #    ports:
  #      - "3000:3000"
  #    depends_on:
  #      - postgres
  #      - adminer
  #    command: yarn start -- -L

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: markets
    volumes:
      - markets-postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:4.0.26
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: markets
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - markets-mongodb-data:/data/mongodb

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  markets-postgres-data:
  markets-mongodb-data:

