version: "2"
services:
  #  markers-server:
  #    build: .
  #    container_name: markers-server
  #    environment:
  #      - NODE_ENV=development
  #    volumes:
  #      - .:/app
  #    ports:
  #      - "3000:3000"
  #    depends_on:
  #      - postgres
  #      - adminer
  #    command: yarn start -- -L

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  #  adminer:
  #    image: adminer
  #    container_name: adminer
  #    restart: always
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - postgres
